### ISSUE TITLE
Microsoft store release

### ISSUE THREAD

**Issue by vanjac** [vanjac/chromafiler#120]
Requirements: https://docs.microsoft.com/en-us/windows/win32/win_cert/certification-requirements-for-windows-desktop-apps

Changes required:
- [x] Must be DPI aware (#71)
- [x] Various required compilation flags
- [ ] Installation should fail cleanly
- [x] Silent install
- [x] Single user install (#107)
- [x] Required installation registry entries
- [ ] Executable signing

**Comment by vanjac** [comment]
https://learn.microsoft.com/en-us/windows/uwp/publish/msiexe/the-app-certification-process

**Comment by vanjac** [comment]
Need to test with a non-admin account

**Comment by vanjac** [comment]
https://www.reddit.com/r/csharp/comments/nuh1ua/who_can_i_trust_code_signing_for_an_opensource/

May need to use MSIX?
